name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: Lantharos/Sabine/.github/workflows/release-app.yml@f65b5799328e573c2e3da1c2183b265972d4f8b3
    with:
      sabine_version: v0.25
      rust_toolchain: "1.95"
      accept_wix_eula: true
      upgrade_from_sabine_version: v0.22
    secrets:
      SABINE_UPDATE_SIGNING_KEY: ${{ secrets.SABINE_UPDATE_SIGNING_KEY }}
