name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: Lantharos/Sabine/.github/workflows/release-app.yml@08fb471de3da1edac6c31d0340b0b91d68be41a4
    with:
      sabine_version: v0.27
      rust_toolchain: "1.95"
      accept_wix_eula: true
      upgrade_from_sabine_version: v0.22
    secrets:
      SABINE_UPDATE_SIGNING_KEY: ${{ secrets.SABINE_UPDATE_SIGNING_KEY }}
