name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: Lantharos/Sabine/.github/workflows/release-app.yml@0b30238c844cfdf9c6c0e3e85f68b161f28391d9
    with:
      sabine_version: v0.28
      rust_toolchain: "1.95"
      accept_wix_eula: true
      upgrade_from_sabine_version: v0.22
    secrets:
      SABINE_UPDATE_SIGNING_KEY: ${{ secrets.SABINE_UPDATE_SIGNING_KEY }}
